### ISSUE TITLE
KeyError: 'Non-existent config key: MODEL.BACKBONE.OUT_CHANNELS'

### ISSUE THREAD

**Issue by robotzheng** [JerryLingjieMei/ADEPT-Model-Release#1]
when I run: 
python3 -m torch.distributed.launch --nproc_per_node=$NGPUS tools/detection_train_net.py --config_file experiments/default_detection.yaml

the logs are:
Traceback (most recent call last):
  File "tools/detection_train_net.py", line 164, in <module>
    main()
  File "tools/detection_train_net.py", line 139, in main
Traceback (most recent call last):
    cfg.merge_from_file(args.config_file)
  File "tools/detection_train_net.py", line 164, in <module>
  File "/usr/local/python3/lib/python3.6/site-packages/yacs/config.py", line 213, in merge_from_file
    self.merge_from_other_cfg(cfg)
  File "/usr/local/python3/lib/python3.6/site-packages/yacs/config.py", line 217, in merge_from_other_cfg
    main()
  File "tools/detection_train_net.py", line 139, in main
    cfg.merge_from_file(args.config_file)
    _merge_a_into_b(cfg_other, self, self, [])
  File "/usr/local/python3/lib/python3.6/site-packages/yacs/config.py", line 213, in merge_from_file
Traceback (most recent call last):
  File "tools/detection_train_net.py", line 164, in <module>
    main()
  File "tools/detection_train_net.py", line 139, in main
Traceback (most recent call last):
    cfg.merge_from_file(args.config_file)
  File "tools/detection_train_net.py", line 164, in <module>
  File "/usr/local/python3/lib/python3.6/site-packages/yacs/config.py", line 213, in merge_from_file
    self.merge_from_other_cfg(cfg)
  File "/usr/local/python3/lib/python3.6/site-packages/yacs/config.py", line 217, in merge_from_other_cfg
    main()
  File "tools/detection_train_net.py", line 139, in main
    cfg.merge_from_file(args.config_file)
    _merge_a_into_b(cfg_other, self, self, [])
  File "/usr/local/python3/lib/python3.6/site-packages/yacs/config.py", line 213, in merge_from_file
  File "/usr/local/python3/lib/python3.6/site-packages/yacs/config.py", line 460, in _merge_a_into_b
Traceback (most recent call last):
  File "tools/detection_train_net.py", line 164, in <module>
    self.merge_from_other_cfg(cfg)
  File "/usr/local/python3/lib/python3.6/site-packages/yacs/config.py", line 217, in merge_from_other_cfg
    _merge_a_into_b(v, b[k], root, key_list + [k])
  File "/usr/local/python3/lib/python3.6/site-packages/yacs/config.py", line 460, in _merge_a_into_b
    main()
  File "tools/detection_train_net.py", line 139, in main
    _merge_a_into_b(cfg_other, self, self, [])
  File "/usr/local/python3/lib/python3.6/site-packages/yacs/config.py", line 460, in _merge_a_into_b
    cfg.merge_from_file(args.config_file)
  File "/usr/local/python3/lib/python3.6/site-packages/yacs/config.py", line 213, in merge_from_file
    _merge_a_into_b(v, b[k], root, key_list + [k])
  File "/usr/local/python3/lib/python3.6/site-packages/yacs/config.py", line 473, in _merge_a_into_b
    _merge_a_into_b(v, b[k], root, key_list + [k])
  File "/usr/local/python3/lib/python3.6/site-packages/yacs/config.py", line 460, in _merge_a_into_b
    self.merge_from_other_cfg(cfg)
  File "/usr/local/python3/lib/python3.6/site-packages/yacs/config.py", line 217, in merge_from_other_cfg
    raise KeyError("Non-existent config key: {}".format(full_key))
KeyError: 'Non-existent config key: MODEL.BACKBONE.OUT_CHANNELS'
    _merge_a_into_b(v, b[k], root, key_list + [k])
  File "/usr/local/python3/lib/python3.6/site-packages/yacs/config.py", line 473, in _merge_a_into_b
    _merge_a_into_b(cfg_other, self, self, [])
  File "/usr/local/python3/lib/python3.6/site-packages/yacs/config.py", line 460, in _merge_a_into_b
Traceback (most recent call last):
  File "tools/detection_train_net.py", line 164, in <module>
    raise KeyError("Non-existent config key: {}".format(full_key))
    _merge_a_into_b(v, b[k], root, key_list + [k])
KeyError: 'Non-existent config key: MODEL.BACKBONE.OUT_CHANNELS'
  File "/usr/local/python3/lib/python3.6/site-packages/yacs/config.py", line 460, in _merge_a_into_b
    main()
  File "tools/detection_train_net.py", line 139, in main
    _merge_a_into_b(v, b[k], root, key_list + [k])
  File "/usr/local/python3/lib/python3.6/site-packages/yacs/config.py", line 473, in _merge_a_into_b
    cfg.merge_from_file(args.config_file)
  File "/usr/local/python3/lib/python3.6/site-packages/yacs/config.py", line 213, in merge_from_file
    self.merge_from_other_cfg(cfg)
  File "/usr/local/python3/lib/python3.6/site-packages/yacs/config.py", line 217, in merge_from_other_cfg
    raise KeyError("Non-existent config key: {}".format(full_key))
KeyError: 'Non-existent config key: MODEL.BACKBONE.OUT_CHANNELS'
    _merge_a_into_b(cfg_other, self, self, [])
  File "/usr/local/python3/lib/python3.6/site-packages/yacs/config.py", line 460, in _merge_a_into_b
    _merge_a_into_b(v, b[k], root, key_list + [k])

**Comment by JerryLingjieMei** [comment]
I believe that maskrcnn benchmark provided by facebook research has changed their config file keys at some time. You may refer to an earlier version of their repo or change the config key corresponding to their current repo.
